---
title: "Regression pressure to status"
author: "Jamie Montgomery"
date: "3/25/2020"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(message = F, warning = F)


library('plm') ### before Tidyverse - 'lead' and 'lag' function conflict
library(tidyverse)
library(caret) ### for cross validation
```

Functions
```{r}
clean_df_names <- function(df) {
  df <- df %>%
    setNames(tolower(names(.)) %>%
               str_replace_all('[^a-z0-9]+', '_') %>%
               str_replace_all('^_+|_+$', ''))
  return(df)
}

calc_d_status <- function(goalname, scores_df, yr_lag) {
  d_stat_df <- scores_df %>%
      filter(goal == goalname) %>%
      mutate(obs_future_status = dplyr::lead(status, yr_lag),
             d_status = (obs_future_status - status) /status) %>%
      filter(!is.na(d_status)) %>%
      filter(!is.infinite(d_status))
  return(d_stat_df)
}

tidy_model <- function(mdl) {
  mdl_df <- mdl %>%
    broom::tidy() %>%
    mutate(adj_r_squared = summary(mdl)$adj.r.squared,
           aicc   = AICcmodavg::AICc(mdl), 
           yrs    = sum(str_detect(term, 'year')),
           rgns   = sum(str_detect(term, 'region')),
           params = rgns + yrs + n() - 1)
  return(mdl_df)
}
```

## Regress changes in status vs. all pressures

Set up dataframe

```{r}
### Set up basic data frame - make sure prs and res are 0-1; status
### range not important here since we'll take a ratio inside a loop.

prs_no_social <- read_csv('prs_no_social.csv') %>%
  select(goal, region_id, year, pressures = score)

scores_rgn_d_status <- read_csv('scores.csv') %>%
  filter(region_id != 0) %>%
  spread(dimension, score) %>%
  select(goal, region_id, year, status, pressures) %>%
  left_join(prs_no_social %>% rename(prs_omit_soc = pressures), 
            by = c('goal', 'region_id', 'year')) %>%
  group_by(goal, region_id) %>%
  arrange(year) %>%
  filter(!is.na(pressures))

goals <- scores_rgn_d_status$goal %>% 
  unique()
```

## Run regression for all goals, all lags
Include a cross validation step.

```{r}
regress_status <- function(df, regr_formula, train_control) {
  d_status_mdl <- lm(regr_formula, data = df)
  d_status_df <- tidy_model(d_status_mdl)

  cross_val_mdl <- train(regr_formula, 
                       data = df, method = "lm",
                       trControl = train_control)
  crossval_df <- cross_val_mdl$results %>%
    clean_df_names()
  
  full_df <- cbind(d_status_df, crossval_df)
  
}
```

Define training control
```{r}
set.seed(123)
train_control <- trainControl(method = "LOOCV")
```

### run regression across all goals and lags
including a cross validation
```{r}
### initialize dataframe
regr_results_lag <- data.frame()

for(yr_lag in 1:6) {
  # yr_lag <- 1
  for(goalname in goals) { # goalname <- 'FIS'

    d_status_df <- calc_d_status(goalname, scores_rgn_d_status, yr_lag)
    
    if(nrow(d_status_df) == 0) next()
    if(length(unique(d_status_df$year)) <= 1) next()
    if(all(is.na(d_status_df$prs_omit_soc))) next()
    test_df <- d_status_df %>%
      group_by(region_id) %>%
      summarize(range_vals = max(status) - min(status))
    
    if(all(test_df$range_vals == 0)) {
      
      regr_results_goal <- data.frame(goal = goalname, lag = yr_lag, model_error = 'no change in status')

    } else {
      
      prs_ecol_df <- regress_status(df = d_status_df, 
                               regr_formula = d_status ~ prs_omit_soc + factor(region_id) + factor(year), 
                               train_control) %>%
        mutate(model = 'prs_ecol_only')
      
      prs_all_df <- regress_status(df = d_status_df, 
                              regr_formula = d_status ~ pressures + factor(region_id) + factor(year), 
                              train_control) %>%
        mutate(model = 'prs_ecol_soc')

      prs_int_only_df <- regress_status(df = d_status_df, 
                              regr_formula = d_status ~ 1 + factor(region_id) + factor(year), 
                              train_control) %>%
        mutate(model = 'intercept only')
      
      regr_results_goal <- bind_rows(prs_ecol_df, prs_all_df, prs_int_only_df) %>%
        mutate(goal = goalname, 
               lag = yr_lag)
      
    }

    regr_results_lag <- bind_rows(regr_results_lag, regr_results_goal)
  }
}

write_csv(regr_results_lag, 'temp/status_prs_results.csv')
```

### clean up results
```{r}
st_prs_mdl <- read_csv('temp/status_prs_results.csv') %>%
  mutate(est_text = formatC(round(estimate, 4), digits = 4, format = 'f'),
         est_text = case_when(p.value < .001 ~ paste0(est_text, '***'),
                              p.value <  .01 ~ paste0(est_text, '**'),
                              p.value <  .05 ~ paste0(est_text, '*'),
                              p.value <  .10 ~ paste0(est_text, '°'),
                              TRUE ~ est_text),
         term = ifelse(str_detect(term, '^prs'), 'pressures', term)) %>%
  select(-std.error, -statistic, -p.value, -intercept, -estimate,
         -rsquared, -mae) %>%
  spread(term, est_text) %>%
  clean_df_names() %>%
  select(-na)

write_csv(st_prs_mdl, 'status_prs_results_formatted_p.csv')

DT::datatable(st_prs_mdl %>% mutate_if(is.numeric, ~ round(., 4)))
```



