---
output:
  word_document: default
  html_document: default
---
### Sea Level Rise

**Layer type:** Pressure

**Data description:** The sea level rise pressure layer is derived from [AVISO+ satellite altimetry data](http://www.aviso.altimetry.fr/en/data/products/sea-surface-height-products/global/msla-mean-climatology.html). Monthly mean sea level anomalies since 1993 track changes in sea level (mm) compared to a reference period from 1993-2012. Raw monthly data are provided on a 0.25x0.25 degree grid. 

**Methods summary:** Data were clipped to within 3 nautical miles of the US Northeast coast, reprojected to US Albers Equal Conic projection and resampled to a grid size of 1km^2^. Monthly data were aggregated and averaged across grid cells to compute mean sea level anomalies. Data was rescaled linearly from 0 to 1 using a reference point equal to 10% larger than the maximum value (0.0845 meters) in the entire Northeast region from 1993-2017 (reference point of 0.093 meters). The current maximum value is unlikely to be the future max, thus setting this reference point allows for an increase in sea level rise pressure into the future. All positive values were divided by 0.093 for rescaling. All negative values were set to zero (i.e., no negative pressure), such that only positive sea level rise values effected the pressure. 

Pressure layer scores were calculated as the mean of rescaled cell values by region and year.

**Gapfilling:** No gapfilling needed.

**References**

The altimeter products were produced by Ssalto/Duacs and distributed by Aviso+, with support from Cnes (https://www.aviso.altimetry.fr).
