---
output:
  html_document: default
  word_document: default
---
### Economic growth

**Layer type(s):** Economies sub-goal layer

**Data description:** NOAA's Economics: National Ocean Watch (ENOW) data provides economic data relevant to ocean sectors at a county level for years 2005 - 2016. Ocean sectors include Living Resources, Marine Construction, Transportation, Ship & Boat Building, Tourism & Recreation, and Offshore Mineral Extraction. ENOW data on annual Gross Domestic Product (GDP) in 2012 US dollars was provided by the National Ocean Economics Program (NOEP) by county and ocean sector.

**Methods summary:** The data was provided by county and also as state-wide totals. From the data we selected GDP values across "All Ocean Sectors", rather than filtering for specific sectors. We also accounted for a data collection change between 2015 and 2016 (from the NOEP website):

> In the recent release of the ENOW series "An additional industry, Fish and Seafood Merchant Wholesalers (NAICS 424460) was added to the Living Resources sector's Seafood Market industry for data years 2016 and beyond. The industry was not applied to earlier years." The addition of this industry significantly distorts annual comparisons and timeline analysis of the Seafood Market sector and Living Resources totals.

To account for this change, we subtracted the 2016 value for Living Resources from All Ocean Sectors, and used the 2015 value for Living instead gapfilling with 2015 data.

After accounting for this, we compared aggregated county data to the state-wide totals and found differences between these two data series. This could be explained by suppressed data at the county level that is included in the state-wide totals. By comparing the absolute values and the temporal trends of the county-aggregated and state-wide totals we made decisions about what data series to use, either the county-level or state-wide totals. 

The state level information was used for Rhode Island, Maine, New York and Connecticut. Since Massachusetts is split into two regions in our region, and the state level trends were similar to the county-aggregated trends, just higher values, we used the county level information. The two data series for New Hampshire differed significantly beginning in 2011 due to data suppression up until that point, where the values across all economic indicators jumps for the state data series. We assumed that if data were not suppressed pre-2011 statewide, we would also see parallel trends in New Hampshire as well. Operating under that assumption, we opted to use the county level data for New Hampshire economic indicators.

Annual GDP growth rate was calculated for each region by comparing each year's GDP total to the average of the previous 3 years. 

**Economies sub-goal layer**  
Each region's GDP growth rate ($g$) is compared to the target of a 3% annual growth ($ref_{max} = 0.03$). This growth target was chosen as it aligns with a widely agreed upon national growth target of between 2-3 % annually (Jones 2016). All regions that achieved a 3% or greater growth rate compared to the average of the previous 3 years received a score of 1. Scores ($eco$) for each region ($i$) and year ($t$)  were scaled linearly so that a score of 0 would be equal to a 30% or greater annual loss in GDP ($ref_{min} = -0.3$), equal to levels seen during the Great Depression:

$$ eco_{i,t} = \begin{cases} 1,& g >= ref_{max},\\
\frac{g-ref_{min}}{ref_{max} - ref_{min}},& g < ref_{max}
\end{cases}$$

**Gapfilling:**  
The first three years of the time series, 2005-2007, were gapfilled with data from 2008 since growth rate was calculated by comparing to the previous three year mean. Since the dataset ends in 2016, these values are carried forward to 2017. There was no spatial gapfilling.

**References:**

National Ocean Economics Program. Ocean Economic Data by Sector & Industry., ONLINE. 2012. Available: http://www.OceanEconomics.org/Market/oceanEcon.asp [9 May 2019]

National Oceanic and Atmospheric Administration (NOAA). Economics: National Ocean Watch (ENOW) Data. Based on data from the Bureau of Labor Statistics and the Bureau of Economic Analysis. Charleston, SC: NOAA Office for Coastal Management.

Jones, C. I. (2016). Chapter 1—The Facts of Economic Growth. In J. B. Taylor & H. Uhlig (Eds.), Handbook of Macroeconomics (Vol. 2, pp. 3–69). Elsevier. https://doi.org/10.1016/bs.hesmac.2016.03.002
