---
output:
  word_document: default
  html_document: default
---
### Salt Marsh extent

**Layer type(s):** Biodiversity Habitats sub-goal layer, Habitat Services Carbon Storage & Coastal Protection sub-goal layer

**Data description:**  

This layer used NOAA's Coastal Change Analysis Program data (C-CAP) to derive an estimate of salt marsh loss from 1996 through 2010 and a collection of historical loss estimates to estimate the overall loss of salt marsh habitat coverage since ~1850s (Table below). 

1. NOAA's Coastal Change Analysis Program (C-CAP) land cover raster data (.img format) available for the years 1996, 2001, 2006 and 2010 for each state in the United States. To measure salt marsh habitats coverage in each of these years we included the following C-CAP land classifications: Estuarine Forested Wetland (16), Estuarine Scrub/Shrub Wetland (17), Estuarine Emergent Wetland (18), Estuarine Aquatic Bed (23).  
 
2. Historical loss references came from two studies

State |	Historical loss (%)	| Reference
------|---------------------|----------
Rhode Island|	53|	Bromberg and Bertness (2005)
Massachusetts|	41|	Bromberg and Bertness (2005)
New Hampshire|	18|	Bromberg and Bertness (2005)
Maine|	0|	Bromberg and Bertness (2005)
Connecticut|	27|	Basso et al. 2015
New York|	48	|Basso et al. 2015


**Methods summary:**  

*Estimating recent salt marsh loss*  
For each time step (1996, 2001, 2006 and 2010) we remove all land cover cells that are not in the four salt marsh categories. The total number of remaining cells is calculated for each time step, and then compared to the 1996 value to get a sense for percent gained or lost since 1996. These values ranged between a 2.5% loss (New York) and a roughly 3% gain (Maine). 

*Incorporating historic loss*  
There has been significant salt marsh lost in the Northeast United States since pre-industrial times. Unfortuantely, the landcover high resolution data only goes back to 1996. To account for historical loss, we looked to the literature for estimates of loss leading up to the 1990's. Both Bromberg and Bertness (2005) and Basso et al. (2015) provide state-level estimates of salt marsh loss since the 1850's. These figures were then added to the calculated habitat loss from the C-CAP data to get more accurate estimates of salt marsh habitat loss.

**Biodiversity: Habitats sub-goal layer**    
The final score for each region and year was equal to the inverse of the amount of salt marsh lost per region. If a region lost 25% of their salt marsh habitat, they would score 75.

**Habitat Services: Carbon Storage sub-goal layer**   
The final score for each region and year was equal to the inverse of the amount of salt marsh lost per region. If a region lost 25% of their salt marsh habitat, they would score 75.

**Habitat Services: Coastal Protection sub-goal layer**   
The final score for each region and year was equal to the inverse of the amount of salt marsh lost per region. If a region lost 25% of their salt marsh habitat, they would score 75.

**Gapfilling**   
The C-CAP data was of high enough resolution that we were able to calculate salt marsh loss in both North and South Massachusetts separately since 1996. But there was no data on historical loss at this scale. Each of these regions were assigned the same amount of historical loss (41%), assuming they lost the same proportion. Linear interpolation was used to gapfill missing data between 2001 and 2010, and the most recent value (2010) was carried forward to 2017.

**References**  
Basso, G., K. O'Brien, M. Albino, and V. O'Neill. "Status and trends of wetlands in the Long Island Sound Area: 130 year assessment." U.S. Department of the Interior, Fish and Wildlife Service. (2015): 37 pp.

Bromberg, Keryn D., and Mark D. Bertness. (2005). "Reconstructing New England salt marsh losses using historical maps." Estuaries 28.6: 823-832.
