---
output:
  html_document: default
  word_document: default
---
### Marine protected areas  

**Layer type(s):** Sense of Place: Lasting Special Places sub-goal layer

**Data description:**   
We use the United States Geological Survey (USGS) Protected Areas Database (PAD) for the US, Version 2.0. This spatial geodatabase contains terrestrial and marine protected areas for the United States. There are 5 layers included in the database, one of which is Marine (`PADUS2_0Marine`). All areas designated as fishery/shellfish management areas as well as the Special Area Management Plans were removed from the outset since these designations are not associated with protection or designation as a special place, but rather for resource management. The database also includes the year of establishment.

### Methods 

The USGS PAD Marine data layer was overlaid with the Northeast OHI regions. The total area protected within each region was calculated. The target for this layer is to have at least 10% of marine area protected. This target reflects the Aichi Target 11 since there is no regional target. All of the marine protected areas were established before 2005, and show no change over the study period.

**Lasting Special Places sub-goal layer**  
Each region is scored from 0 to 1 by comparing the amount of marine protected areas to their total area. If 10% or more is protected, the region receives a 1. Scores linearly decrease to 0 for no protected areas.

**Gapfilling**  
No gapfilling was necessary.

**References**  
U.S. Geological Survey (USGS) Gap Analysis Project (GAP), 2018, Protected Areas Database of the United States (PAD-US): U.S. Geological Survey data release, https://doi.org/10.5066/P955KPLE. [Downloaded June 5, 2019]
