---
output:
  word_document: default
  html_document: default
---
### Aquaculture production

**Layer type(s):** Aquaculture sub-goal layer  

**Data description(s):**    
Production data was gathered from available state reports (e.g. CRMC’s “Aquaculture in Rhode Island”, Massachusetts DF&G reports). Since this data often exists within PDF’s and various formats, all production data was entered by hand into a google sheet.

**Methods summary**  
The raw data was cleaned so that all units of production were in pounds according to the conversion table below:

Species |	Pounds|	Bushel	|Bag	|Individual
--------|-------|---------|-----|----------
Hard Clam |	1	|0.017|	0.048	|10.00
Quahog	|1	|0.017	|NA	|10.00
Soft Shell Clams	|1	|0.020	|NA|	NA
Bay Scallop	|1	|0.014|	NA|	NA
Oysters	|1	|0.017|	0.017|	2.36
Clams	|1	|0.017	|NA	|NA
Scallops	|1	|0.014	|NA|	NA

Species names were harmonized, e.g. "Quahog" and "Clams" were assigned the shared name "Hard Clams". A three year rolling mean was applied to production to account for year to year variability.

**Aquaculture sub-goal layer**    
The final layer includes total production in pounds of each species farmed in each region over time.

**Gapfilling:**   
Some regions had missing data for years and required gapfilling.

Maine's Department of Marine Resources (DMR) does not report Atlantic salmon production data after 2010 due to confidentiality statutes. Based on communication with experts in the region, we know that Atlantic salmon production does not stop after 2010. Without any other information, we gapfilled 2011 - 2017 with the same 2010 production data reported by Maine's DMR.

Massachusetts was missing 2012 and 2013 for Hard Clam and Oysters, and Rhode Island was missing 2010 for Oysters and Hard Clam. We didn’t know if these were true 0’s, indicating no production, or missing data. Since we calculate a rolling average of production, NAs will remain as NA’s and the average will rely on just one or two years of catch. This is done to account for any wild fluctuations in catch year to year.

**References:**
*Rhode Island*  
Aquaculture Situation and Outlook Report 2009: Rhode Island  
Coastal Resources Management Council, Aquaculture in Rhode Island - Annual Status Reports (1999 - 2015)

*Maine*  
Maine Department of Marine Resources Aquaculture Harvest Data. https://www.maine.gov/dmr/aquaculture/harvestdata/index.html.  
Aquaculture Situation and Outlook Report 2009: Maine

*Massachusetts*   
Department of Fish and Game Massachusetts Marine Fisheries Annual Report (2011-2017).  
Aquaculture Situation and Outlook Report 2009: Massachusetts  

*New York*  
Aquaculture Situation and Outlook Report 2009: New York  
Shellfish Harvested in Long Island Sound. https://longislandsoundstudy.net/ecosystem-target-indicators/shellfish-harvested/

*Connecticut*  
Aquaculture Situation and Outlook Report 2009: Connecticut  
Shellfish Harvested in Long Island Sound. https://longislandsoundstudy.net/ecosystem-target-indicators/shellfish-harvested/

*New Hampshire*  
New Hampshire Fish and Game Biennial Reports (2015, 2017, 2019)  
Aquaculture Situation and Outlook Report 2010: New Hampshire
