---
output:
  word_document: default
  html_document: default
---
### Disease from Aquaculture

**Layer type:** Pressure

**Data description:**   
There was no specific data that measured current farm impacts on seabed habitats that was consistent region wide, so we relied on a proxy dataset instead.

Sustainability scores for farmed species were obtained from the Monterey Bay Aquarium Seafood Watch Seafood Recommendations. This assessment incorporates 10 criteria: availability and robustness of data, effluent discharge, effects on habitats, use of chemicals, escapes during production, disease (pathogen, and parasite interaction), stock source, predator and wildlife moralities, and escapes during transit when calculating the overall sustainability score. We used the *disease, pathogen, and parasite interaction* criteria to inform the contribution of aquaculture production to the species pollution layer. The criteria assesses the increases in transmission or retransmission of diseases or pathogens to wild fish stocks due to the amplification caused by aquaculture production.

**Methods summary**    
One of the observed side effects during aquaculture production is the increased prevalence of disease, pathogens, and parasite spreading in the farms due to high densities of individuals (Bondad-Reantaso et al. 2005). These can spread out through neighboring water bodies and infect wild stocks.

To calculate the score for this layer we rescaled the criteria score from 0-10 to 0-1, scaled the production by multiplying it with the new criteria score, summed up all the scaled production in each region, and then divided it by the total area of the region to distribute the pressures. Since we know that aquaculture production is in the early stages and will likely grow much larger than the current production levels, we used a reference point of twice the current maxium of the scaled distributed production in each region, and then rescaled the pressure score 0-1.

**Gapfilling**    
The only gapfilling used in this layer is the same that was applied for the Aquaculture Production layer since that layer was used to derive this pressure layer.

**References**      
Monterey Bay Aquarium Seafood Watch, available at: https://www.seafoodwatch.org/seafood-recommendations

Bondad-Reantaso, M. G., Subasinghe, R. P., Arthur, J. R., Ogawa, K., Chinabut, S., Adlard, R., et al. (2005). Disease and health management in Asian aquaculture. Veterinary Parasitology 132, 249–272. doi:10.1016/j.vetpar.2005.07.005.
