---
output:
  html_document: default
  word_document: default
---
### Fisheries resource access

**Layer type(s):** Resource Access Opportunities goal layer  

**Data description(s)**    
The fish resource access layer was derived from NOAA’s Fish Stock Sustainability Index (FSSI). This data combines information from stock assessments to measure stock sustainability on a 0-4 scale for 47 stocks in the Northeast for all years 2005 - 2018.

**Methods summary**  
The raw data included stock name and location. Using this information, each stock was matched to an OHI region where it is found using the fisheries landings data used in the Wild-Caught Fisheries goal. Once the stocks were matched with OHI regions, each stock FSSI score was divided by 4 to convert scores into a 0 to 1 scale.

**Resource Access Opportunities layer**    
Each region's score is equal to the mean score of all stocks in the region and year.

**Gapfilling**   
There was no gapfilling

**References**  
NOAA Fisheries Stock Sustainability Index. 2019. Emailed 29 July 2019. https://www.fisheries.noaa.gov/national/population-assessments/status-us-fisheries#fish-stock-sustainability-index.
