---
output:
  html_document: default
  word_document: default
---
### Commercial fishing engagement

**Layer type:** Sense of Place: Fishing Engagement Sub-goal layer

**Data description:**   
The commercial fishing engagement layer is derived from NOAA Fisheries Community Social Vulnerability Indicators dataset. 

> Social indicators are numerical measures that describe the well-being of individuals or communities. Indicators are comprised of one variable or several components combined into an index. They are used to describe and evaluate community well-being in terms of social, economic, and psychological welfare. In this study, a set of 13 indices have been developed to measure Social Vulnerability, Gentrification Pressure, Sea Level Rise Risk, and Fishing Dependence (both commercial and recreational) of coastal communities in the U.S.

This dataset contains indicator rankings (Low, Medium Low, Medium High and High) for coastal counties across many coastal US states for the years 2009 - 2016. This layer specifically used the Commercial Fishing Engagement indicator. Time series indicator data and the coastal communities shapefile was provided by NOAA via direct contact.

**Methods summary**   
The commercial fishing engagement indicator measures the presence of commercial fishing through fishing activity as shown through permits and vessel landings. We only wanted to include communities that touch the coast. Many of the counties included in the full dataset are not truly coastal (no boundary along the ocean or waterway). The first step was to use our inland 1km buffer on the coastal county shapefile provided by NOAA to select the coastal counties we were interested in by region.

We then subset the commercial fishing engagement indicator data and divide the Index score for each community (1-4) by 4, then take the mean across all communities in the region per year. 
 
**Fishing Engagement sub-goal layer**   
The target for this layer was set to be 10% higher than the highest observed value across all regions and years. For this layer that target was 0.474. The score for each region and year was equal to their coastal community mean aggregated score divided by this reference point.

**Gapfilling**    
Temporal gapfilling was necessary since this dataset only has data for 2009-2016. All years 2005-2008 were backfilled with the 2009 data, and 2017 was gapfilled with the 2016 data.

**References**    
NOAA Fisheries Office of Science and Technology. (2019). NOAA Fisheries Community Social Vulnerability Indicators (CSVIs). Version 3.  https://www.fisheries.noaa.gov/national/socioeconomics/social-indicators-fishing-communities

Jepson, M., Colburn, L, L. (2013). Development of Social Indicators of Fishing Community Vulnerability and Resilience in the U.S. Southeast and Northeast Regions. U.S. Dept. of Commerce., NOAA Technical Memorandum NMFS-F/SPO-129, 64 p
