---
output:
  html_document: default
  word_document: default
---
### Job growth

**Layer type(s):** Tourism & Recreation goal layer  

**Data description(s):**   
1. NOAA's Economics: National Ocean Watch (ENOW) data provides economic data relevant to ocean sectors at a county level for years 2005 - 2016. Ocean sectors include Living Resources, Marine Construction, Transportation, Ship & Boat Building, Tourism & Recreation, and Offshore Mineral Extraction. ENOW data on annual employment was provided by the National Ocean Economics Program (NOEP) by county and ocean sector.

2. Bureau of Labor Statistics (BLS) data on national employment. Specifically, the data series with ID: ENUUS00010010, "All Employees in Total Covered Total, all industries for All establishment sizes in U.S. TOTAL." This data was accessed from R using the R package `blscrapeR`.

**Methods summary:** The data was provided by county and also as state-wide totals. From the data we selected wages across "All Ocean Sectors", rather than filtering for specific sectors. We also accounted for a data collection change between 2015 and 2016 (from the NOEP website):

> In the recent release of the ENOW series "An additional industry, Fish and Seafood Merchant Wholesalers (NAICS 424460) was added to the Living Resources sector's Seafood Market industry for data years 2016 and beyond. The industry was not applied to earlier years." The addition of this industry significantly distorts annual comparisons and timeline analysis of the Seafood Market sector and Living Resources totals.

To account for this change, we subtracted the 2016 value for Living Resources from All Ocean Sectors, and used the 2015 value for Living instead gapfilling with 2015 data.

After accounting for this, we compared aggregated county data to the state-wide totals and found differences between these two data series. This could be explained by suppressed data at the county level that is included in the state-wide totals. By comparing the absolute values and the temporal trends of the county-aggregated and state-wide totals we made decisions about what data series to use, either the county-level or state-wide totals. 

The state level information was used for Rhode Island, Maine, New York and Connecticut. Since Massachusetts is split into two regions in our region, and the state level trends were similar to the county-aggregated trends, just higher values, we used the county level information. The two data series for New Hampshire differed significantly beginning in 2011 due to data suppression up until that point, where the values across all economic indicators jumps for the state data series. We assumed that if data were not suppressed pre-2011 statewide, we would also see parallel trends in New Hampshire as well. Operating under that assumption, we opted to use the county level data for New Hampshire economic indicators.

We calculated annual job growth rates and compared total employment that year to the average number of jobs over the previous 3 years. Because there is no absolute reference point for employment (i.e., a target number would be completely arbitrary), this layer uses a moving baseline as the reference point. The reference for regions job growth is set to be equal to or greater than the national average that year, calculated using data from the Bureau of Labor Statistics. This reflects an implicit goal of maintaining coastal employment on short time scales, allowing for decadal or generational shifts in what people want and expect.

Annual job growth rates for each region was calculated by comparing each year's total employment numbers to the national job growth rate, calculated using the United States Bureau of Labor Statistics data on national employment (series ENUUS00010010).

**Livelihoods sub-goal layer**  
Each region's mean employment growth rate ($g_{i}$) is compared to the national average over the same time period ($g_{n}$). If national job growth is positive, a region will score a 1 if it is greater than or equal to the national job growth rate. If national job growth is negative, we want coastal job growth to be the same or better than the region's job growth over the previous 3 years. A loss of 25% of jobs compared to the previous 3 years results in a score of 0. This reference point ($ref_{min}$ = 0.25) is equal to what was experienced during the Great Depression.


$$ j_{i,t} = \begin{cases} \frac{ref_{min} + g_{i}}{ref_{min} + g_{n}},& g_{n} >= 0,\\
\frac{ref_{min} + g_{i}}{ref_{min}},& g_{n} < 0
\end{cases}$$


**Gapfilling:**  
The first three years of the time series, 2005-2007, were gapfilled with data from 2008 since growth rate was calculated by comparing to the previous three year mean. Since the dataset ends in 2016, these values are carried forward to 2017. There was no spatial gapfilling.

**References:**

National Ocean Economics Program. Ocean Economic Data by Sector & Industry., ONLINE. 2012. Available: http://www.OceanEconomics.org/Market/oceanEcon.asp [9 May 2019]

National Oceanic and Atmospheric Administration (NOAA). Economics: National Ocean Watch (ENOW) Data. Based on data from the Bureau of Labor Statistics and the Bureau of Economic Analysis. Charleston, SC: NOAA Office for Coastal Management.

Kris Eberwein (2019). blscrapeR: An API Wrapper for the Bureau of Labor Statistics (BLS). R package version 3.2.0. https://CRAN.R-project.org/package=blscrapeR
